Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "server.py", line 39, in run
    self.obj.thread_db(self.obj)
  File "/usr/local/shadowsocksr/db_transfer.py", line 232, in thread_db
    db_instance = obj()
  File "/usr/local/shadowsocksr/db_transfer.py", line 297, in __init__
    self.load_cfg()
  File "/usr/local/shadowsocksr/db_transfer.py", line 303, in load_cfg
    with open(config_path, 'rb+') as f:
IOError: [Errno 2] No such file or directory: 'usermysql.json'

IPv6 support
